# Generated by Django 3.0.5 on 2020-05-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Y', models.FloatField(help_text='Latitude', max_length=100)),
                ('X', models.FloatField(help_text='Longitude', max_length=100)),
                ('UniqueID', models.CharField(help_text='Unique Squirrel ID', max_length=100)),
                ('Shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=20)),
                ('Date', models.DateField()),
                ('Age', models.CharField(choices=[('Kitten', 'Kitten'), ('Adult', 'Adult')], max_length=100, null=True)),
                ('Fur', models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon')], help_text='Primary Fur Color', max_length=10)),
                ('Location', models.CharField(blank=True, max_length=100, null=True)),
                ('Spec_location', models.CharField(help_text='Location', max_length=100, null=True)),
                ('Running', models.BooleanField(default=False)),
                ('Chasing', models.BooleanField(default=False)),
                ('Climbing', models.BooleanField(default=False)),
                ('Eating', models.BooleanField(default=False)),
                ('Foraging', models.BooleanField(default=False)),
                ('Other_activities', models.CharField(max_length=100, null=True)),
                ('Kuks', models.BooleanField(default=False)),
                ('Quaas', models.BooleanField(default=False)),
                ('Moans', models.BooleanField(default=False)),
                ('Tail_Flags', models.BooleanField(default=False)),
                ('Tail_Twitches', models.BooleanField(default=False)),
                ('Approaches', models.BooleanField(default=False)),
                ('Indifferent', models.BooleanField(default=False)),
                ('Runs_From', models.BooleanField(default=False)),
            ],
        ),
    ]
